[[redirects]]
  from = '/api/*'
  to = 'https://meydit-project.herokuapp.com/api/:splat'
  status = 200

[[redirects]]
  from = '/api/posts/'
  to = 'https://meydit-project.herokuapp.com/api/posts'
  status = 200
[[redirects]]
  from = '/*'
  to = '/index.html'
  status = 200